[project]
name = "highlights-search"
version = "0.1.0"
description = "Semantic search for my reading highlights"

[project.dependencies]
boto3 = "1.26.90"

[project.dev-dependencies]
chalice = "^1.29.0"

[tool.poetry]
name = "highlights-search"
version = "0.1.0"
description = "Semantic search for my highlights"
authors = ["Sawyer <git@sawyerh.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "1.26.90"
pandas = "^2.0.3"

[tool.poetry.group.dev.dependencies]
chalice = "^1.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
