service: highlights-search

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  # "...significantly better price and performance"
  # https://docs.aws.amazon.com/lambda/latest/dg/foundation-arch.html#foundation-arch-adv
  architecture: arm64
  iam:
    role:
      # Allow the Lambda to read from the S3 bucket
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::sawyer-sandbox/*
  # Enable AWS X-Ray tracing:
  tracing:
    lambda: true

package:
  patterns:
    - "!.venv/**"
    - "!__pycache__/**"
    - "!tmp/**"

functions:
  search:
    handler: handler.lambda_handler
    name: highlights-search-${sls:stage}
    url: true
    timeout: 60
    layers:
      - !Ref PythonRequirementsLambdaLayer
      # https://aws-sdk-pandas.readthedocs.io/en/stable/layers.html
      - arn:aws:lambda:${aws:region}:336392948345:layer:AWSSDKPandas-Python310-Arm64:3
      # https://docs.powertools.aws.dev/lambda/python/latest/
      - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:37
    environment:
      OPENAI_API_KEY: ${ssm:/aws/reference/secretsmanager/Highlights/OpenAI-API-Key}
      POWERTOOLS_SERVICE_NAME: ${self:service}-${sls:stage}
      POWERTOOLS_METRICS_NAMESPACE: ${self:service}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true
    slim: true
