# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: "AWS::Serverless-2016-10-31"

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  highlightsEmailToFirebase:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      FunctionName: highlightsEmailToFirebase
      Description: Send highlights to Firebase (Firestore DB)
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100 # seconds
      Role: !GetAtt highlights_email_lambda_s3_role.Arn
      Environment:
        Variables:
          KEY_PREFIX: !Ref KEY_PREFIX
          S3_BUCKET: !Ref S3_BUCKET
          SERVICE_ACCOUNT: !Ref SERVICE_ACCOUNT
